// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvY4_mnCsXC59O8BQsNqZFSioOpEzipU',
    appId: '1:96819798531:web:d9800056d0960a9f372436',
    messagingSenderId: '96819798531',
    projectId: 'datahack-2c661',
    authDomain: 'datahack-2c661.firebaseapp.com',
    storageBucket: 'datahack-2c661.firebasestorage.app',
    measurementId: 'G-SSEECTJTK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDat4T6PVPIKGRg6OyV6yuBuZaLVBHBpWc',
    appId: '1:96819798531:android:399b6ce2d3b44a23372436',
    messagingSenderId: '96819798531',
    projectId: 'datahack-2c661',
    storageBucket: 'datahack-2c661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaxv5BlhA5mCH272yZgDc448VvKPSPZY',
    appId: '1:96819798531:ios:d2791556de0fb0b7372436',
    messagingSenderId: '96819798531',
    projectId: 'datahack-2c661',
    storageBucket: 'datahack-2c661.firebasestorage.app',
    iosBundleId: 'com.example.datahack3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaxv5BlhA5mCH272yZgDc448VvKPSPZY',
    appId: '1:96819798531:ios:d2791556de0fb0b7372436',
    messagingSenderId: '96819798531',
    projectId: 'datahack-2c661',
    storageBucket: 'datahack-2c661.firebasestorage.app',
    iosBundleId: 'com.example.datahack3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOvY4_mnCsXC59O8BQsNqZFSioOpEzipU',
    appId: '1:96819798531:web:288b742a83cdf4e4372436',
    messagingSenderId: '96819798531',
    projectId: 'datahack-2c661',
    authDomain: 'datahack-2c661.firebaseapp.com',
    storageBucket: 'datahack-2c661.firebasestorage.app',
    measurementId: 'G-QMJY7M3KCG',
  );
}
